<div class="ails-segment" style="margin-top: 0">
    <h2><?php echo __('HOW IT WORKS (IMPORTANT)', "automatic-internal-links-for-seo"); ?></h2>

    <p><strong><?php echo __('SYNC / AUTO LINKS:', "automatic-internal-links-for-seo"); ?></strong> <?php echo __( 'Got hundreds / thousands of internal links to create (SEO)? This plugin allows you to automate the internal linking process by using the "Focus keywords" that you have deployed with Yoast or Rank Math for your pages, articles and products, as "keywords" to find in your content. The plugin will identify each of the "Focus Keywords" as well as the pages where these "Focus Keywords" were found, then, will scan your content for these words. Once found, it will automatically link them to the page where these words (focus keywords) have been found.', "automatic-internal-links-for-seo" ); ?></p>

    <p><strong><?php echo __('SYNC CONTINUOUSLY (PRO):', "automatic-internal-links-for-seo"); ?></strong> <?php echo __( 'This feature allows you to perform the "SYNC" process continuously. So, each time you add a page, an article, a product to your site (this also works if you modify the "Focus Keyword" of an existing page), the plugin will identify the "focus Keywords" used and will search in your site an identical word to link to.', "automatic-internal-links-for-seo" ); ?></p>

    <p><strong><?php echo __('CHECK ACTIVITY LOG:', "automatic-internal-links-for-seo"); ?></strong> <?php echo __( 'After performing the synchronization, you can check all the links that have been created on your site, with the date, the link created and the word used.', "automatic-internal-links-for-seo" ); ?></p>

    <p><strong><?php echo __('META BOX:', "automatic-internal-links-for-seo"); ?></strong> <?php echo __( 'If, during synchronization, you want to prevent a page, an article, a product from being modified (with the creation of links in its content), you can either, use the META BOX deployed on all pages, or, you can list in the "Blacklisting" section the URLs of pages, articles, products not to be modified.', "automatic-internal-links-for-seo" ); ?></p>

    <p><strong><?php echo __('CUSTOM LINKS:', "automatic-internal-links-for-seo"); ?></strong> <?php echo __( 'This functionality allows you to create 2 types of link: either internal links or external links. Regarding internal links, it may happen that you want to create links from words other than those used for the "Focus Keywords", in this case, all you need is the "Custom Internal Links" feature. If, still in an SEO context, you want to create external links, you can use the "External links" feature (we recommend that you activate the "NoFollow" attribute each time for external links).', "automatic-internal-links-for-seo" ); ?></p>
</div>

<?php include "promos.view.php"; ?>